version: '3.8'
services:
  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: intelldocs
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend-node:
    build: ./backend/node
    env_file:
      - ./backend/node/.env.example
    ports:
      - "4000:4000"
    depends_on:
      - mongo
      - postgres
  backend-python:
    build: ./backend/python
    ports:
      - "5001:5001"
      - "5002:5002"
  frontend:
    build: ./frontend/nextjs
    ports:
      - "3000:3000"
    depends_on:
      - backend-node
volumes:
  mongo_data:
  pg_data:
