openapi: 3.0.0
info:
  title: Intelldocs AI API
  version: 1.0.0
  description: API documentation for the Intelldocs AI platform
servers:
  - url: http://localhost:4000/api
paths:
  /register:
    post:
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                role:
                  type: string
      responses:
        '201':
          description: User registered
        '409':
          description: User already exists
  /users/login:
    post:
      summary: Login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: JWT token
  /documents/upload:
    post:
      summary: Upload a document
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        '200':
          description: Document uploaded and analyzed
  /approvals/request:
    post:
      summary: Request approval for a document
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                documentId:
                  type: string
                approverId:
                  type: string
      responses:
        '200':
          description: Approval requested
  /notifications:
    get:
      summary: Get notifications for the logged-in user
      security:
        - bearerAuth: []
      responses:
        '200':
          description: List of notifications
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
